In [1]:
import cv2
import numpy as np
import os
import glob
 
# Defining the dimensions of checkerboard
CHECKERBOARD = (6,9)
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
 
# Creating vector to store vectors of 3D points for each checkerboard image
objpoints = []
# Creating vector to store vectors of 2D points for each checkerboard image
imgpoints = [] 
 
 
# Defining the world coordinates for 3D points
objp = np.zeros((1, CHECKERBOARD[0] * CHECKERBOARD[1], 3), np.float32)
objp[0,:,:2] = np.mgrid[0:CHECKERBOARD[0], 0:CHECKERBOARD[1]].T.reshape(-1, 2)
prev_img_shape = None
 
# Extracting path of individual image stored in a given directory
images = glob.glob('./Images/*.jpg')
for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    # Find the chess board corners
    # If desired number of corners are found in the image then ret = true
    ret, corners = cv2.findChessboardCorners(gray, CHECKERBOARD, cv2.CALIB_CB_ADAPTIVE_THRESH + cv2.CALIB_CB_FAST_CHECK + cv2.CALIB_CB_NORMALIZE_IMAGE)
     
    """
    If desired number of corner are detected,
    we refine the pixel coordinates and display 
    them on the images of checker board
    """
    if ret == True:
        objpoints.append(objp)
        # refining pixel coordinates for given 2d points.
        corners2 = cv2.cornerSubPix(gray, corners, (11,11),(-1,-1), criteria)
         
        imgpoints.append(corners2)
 
        # Draw and display the corners
        img = cv2.drawChessboardCorners(img, CHECKERBOARD, corners2, ret)
     
    cv2.imshow('img',img)
    cv2.waitKey(0)
 
cv2.destroyAllWindows()
 
h,w = img.shape[:2]
 
"""
Performing camera calibration by 
passing the value of known 3D points (objpoints)
and corresponding pixel coordinates of the 
detected corners (imgpoints)
"""
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)
 
print("Camera matrix : \n")
print(mtx)
print("dist : \n")
print(dist)
print("rvecs : \n")
print(rvecs)
print("tvecs : \n")
print(tvecs)

Camera matrix : 

[[536.07343019   0.         342.37038789]
 [  0.         536.01634475 235.53685636]
 [  0.           0.           1.        ]]
dist : 

[[-0.26509006 -0.0467439   0.00183301 -0.00031471  0.25231586]]
rvecs : 

(array([[-0.22584693],
       [ 1.01551139],
       [-2.79470629]]), array([[ 0.48287252],
       [-0.17036999],
       [-1.40740334]]), array([[0.0652592 ],
       [0.44701844],
       [0.10800011]]), array([[-0.47359526],
       [ 0.08970848],
       [-0.22605978]]), array([[ 0.05280146],
       [-0.60171822],
       [-0.18453822]]), array([[ 0.49542331],
       [ 0.11948823],
       [-0.29675962]]), array([[-0.35339067],
       [ 0.24071879],
       [ 0.20970029]]), array([[-0.27527336],
       [ 0.10123358],
       [-1.56296566]]), array([[-0.08398744],
       [ 0.34802802],
       [-1.54244125]]), array([[-0.1014161 ],
       [ 0.32034834],
       [ 0.3147293 ]]), array([[-0.37463359],
       [ 0.06982834],
       [-0.01937108]]), array([[-0.34698247],
    

In [1]:
import numpy as np
import cv2 as cv
import glob
# termination criteria
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)
# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((6*7,3), np.float32)
objp[:,:2] = np.mgrid[0:7,0:6].T.reshape(-1,2)
# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.
images = glob.glob('./Images/*.jpg')
for fname in images:
    img = cv.imread(fname)
    gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
    # Find the chess board corners
    ret, corners = cv.findChessboardCorners(gray, (7,6), None)
    # If found, add object points, image points (after refining them)
    if ret == True:
        objpoints.append(objp)
        corners2 = cv.cornerSubPix(gray,corners, (11,11), (-1,-1), criteria)
        imgpoints.append(corners2)
        # Draw and display the corners
        cv.drawChessboardCorners(img, (7,6), corners2, ret)
        cv.imshow('img', img)
        #cv.waitKey(500)
cv.destroyAllWindows()

In [7]:
objp[40]

array([5., 5., 0.], dtype=float32)

In [3]:
import cv2
import numpy as np
import os
import glob
  
  
# Define the dimensions of checkerboard
CHECKERBOARD = (6, 9)
  
  
# stop the iteration when specified
# accuracy, epsilon, is reached or
# specified number of iterations are completed.
criteria = (cv2.TERM_CRITERIA_EPS + 
            cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
  
  
# Vector for 3D points
threedpoints = []
  
# Vector for 2D points
twodpoints = []
  
  
#  3D points real world coordinates
objectp3d = np.zeros((1, CHECKERBOARD[0] 
                      * CHECKERBOARD[1], 
                      3), np.float32)
objectp3d[0, :, :2] = np.mgrid[0:CHECKERBOARD[0],
                               0:CHECKERBOARD[1]].T.reshape(-1, 2)
prev_img_shape = None
  
  
# Extracting path of individual image stored
# in a given directory. Since no path is
# specified, it will take current directory
# jpg files alone
images = glob.glob('./Images/*.jpg')
  
for filename in images:
    image = cv2.imread(filename)
    print(type(image))
    break
    grayColor = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
  
    # Find the chess board corners
    # If desired number of corners are
    # found in the image then ret = true
    ret, corners = cv2.findChessboardCorners(
                    grayColor, CHECKERBOARD, 
                    cv2.CALIB_CB_ADAPTIVE_THRESH 
                    + cv2.CALIB_CB_FAST_CHECK + 
                    cv2.CALIB_CB_NORMALIZE_IMAGE)
  
    # If desired number of corners can be detected then,
    # refine the pixel coordinates and display
    # them on the images of checker board
    if ret == True:
        threedpoints.append(objectp3d)
  
        # Refining pixel coordinates
        # for given 2d points.
        corners2 = cv2.cornerSubPix(
            grayColor, corners, (11, 11), (-1, -1), criteria)
  
        twodpoints.append(corners2)
  
        # Draw and display the corners
        image = cv2.drawChessboardCorners(image, 
                                          CHECKERBOARD, 
                                          corners2, ret)
  
    cv2.imshow('img', image)
    cv2.waitKey(100)
  
cv2.destroyAllWindows()
  
h, w = image.shape[:2]
  
  
# Perform camera calibration by
# passing the value of above found out 3D points (threedpoints)
# and its corresponding pixel coordinates of the
# detected corners (twodpoints)
ret, matrix, distortion, r_vecs, t_vecs = cv2.calibrateCamera(
    threedpoints, twodpoints, grayColor.shape[::-1], None, None)
  
  
# Displaying required output
print(" Camera matrix:")
print(matrix)
  
print("\n Distortion coefficient:")
print(distortion)
  
print("\n Rotation Vectors:")
print(r_vecs)
  
print("\n Translation Vectors:")
print(t_vecs)

<class 'numpy.ndarray'>


NameError: name 'grayColor' is not defined

In [35]:
import cv2
import numpy as np
import os
import glob



def draw(img, corners, imgpts):
    imgpts = (np.rint(imgpts)).astype(int)
    corner = tuple(corners[0].ravel())
    corner_1 = tuple(corners[0].ravel())
    corner_2 = tuple(corners[8].ravel())
    corner_3 = tuple(corners[0].ravel())
    x = [int(i) for a, i in enumerate(corner)]
    corner = tuple(x)
    img = cv2.line(img, corner, tuple(imgpts[0].ravel()), (255,0,0), 5)
    img = cv2.line(img, corner, tuple(imgpts[1].ravel()), (0,255,0), 5)
    img = cv2.line(img, corner, tuple(imgpts[2].ravel()), (0,0,255), 5)
    return img



# Define the dimensions of checkerboard
CHECKERBOARD = (6, 9)
  
  
# stop the iteration when specified
# accuracy, epsilon, is reached or
# specified number of iterations are completed.
criteria = (cv2.TERM_CRITERIA_EPS + 
            cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
  
  
# Vector for 3D points
threedpoints = []
  
# Vector for 2D points
twodpoints = []


#  3D points real world coordinates
objectp3d = np.zeros((1, CHECKERBOARD[0] 
                      * CHECKERBOARD[1], 
                      3), np.float32)
objectp3d[0, :, :2] = np.mgrid[0:CHECKERBOARD[0],
                               0:CHECKERBOARD[1]].T.reshape(-1, 2)
prev_img_shape = None
  
  
# Extracting path of individual image stored
# in a given directory. Since no path is
# specified, it will take current directory
# jpg files alone
#images = glob.glob('./Images/*.jpg')
video_feed = cv2.VideoCapture(0)
video_feed.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)
video_feed.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)
i = 0
axis = np.float32([[3,0,0], [0,3,0], [0,0,-3]]).reshape(-1,3)
while i < 100:
    _, image = video_feed.read()
    #cv2.imshow('frame', image)
    grayColor = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    #print(i)
    i = i + 1
    # Find the chess board corners
    # If desired number of corners are
    # found in the image then ret = true
    ret, corners = cv2.findChessboardCorners(
                    grayColor, CHECKERBOARD, 
                    cv2.CALIB_CB_ADAPTIVE_THRESH 
                    + cv2.CALIB_CB_FAST_CHECK + 
                    cv2.CALIB_CB_NORMALIZE_IMAGE)
  
    # If desired number of corners can be detected then,
    # refine the pixel coordinates and display
    # them on the images of checker board
    if ret == True:
        threedpoints.append(objectp3d)
  
        # Refining pixel coordinates
        # for given 2d points.
        corners2 = cv2.cornerSubPix(
            grayColor, corners, (11, 11), (-1, -1), criteria)
  
        twodpoints.append(corners2)
  
        # Draw and display the corners
        image = cv2.drawChessboardCorners(image, 
                                          CHECKERBOARD, 
                                          corners2, ret)
        ret, matrix, distortion, r_vecs, t_vecs = cv2.calibrateCamera(
        threedpoints, twodpoints, grayColor.shape[::-1], None, None)
        #print(matrix)
        imgpts, jac = cv2.projectPoints(axis, r_vecs[0], t_vecs[0], matrix, distortion)
        img = draw(image,corners2,imgpts)
        cv2.imshow('img',img)
        #print(len(r_vecs))
        
  
    cv2.imshow('img', image)
    cv2.waitKey(100)
  
cv2.destroyAllWindows()
  
h, w = image.shape[:2]
  
  
# Perform camera calibration by
# passing the value of above found out 3D points (threedpoints)
# and its corresponding pixel coordinates of the
# detected corners (twodpoints)
# ret, matrix, distortion, r_vecs, t_vecs = cv2.calibrateCamera(
#     threedpoints, twodpoints, grayColor.shape[::-1], None, None)
  
  
# Displaying required output
# print(" Camera matrix:")
# print(matrix)
  
# print("\n Distortion coefficient:")
# print(distortion)
  
# print("\n Rotation Vectors:")
# print(r_vecs)
  
# print("\n Translation Vectors:")

# print(t_vecs)

In [19]:
rotation, _ = cv2.Rodrigues(r_vecs[5])
rotation

array([[-0.00187698,  0.35496061,  0.93487937],
       [-0.86273454,  0.472152  , -0.18100164],
       [-0.50565362, -0.80689246,  0.30535056]])

In [26]:
import numpy as np
import cv2 as cv



def draw(img, corners, imgpts):
    corner = tuple(corners[0].ravel())
    img = cv.line(img, corner, tuple(imgpts[0].ravel()), (255,0,0), 5)
    img = cv.line(img, corner, tuple(imgpts[1].ravel()), (0,255,0), 5)
    img = cv.line(img, corner, tuple(imgpts[2].ravel()), (0,0,255), 5)
    return img
CHECKERBOARD = (6, 9)
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)
objp = np.zeros((1, CHECKERBOARD[0] 
                      * CHECKERBOARD[1], 
                      3), np.float32)
objp[0, :, :2] = np.mgrid[0:CHECKERBOARD[0],
                               0:CHECKERBOARD[1]].T.reshape(-1, 2)
axis = np.float32([[3,0,0], [0,3,0], [0,0,-3]]).reshape(-1,3)

video_feed = cv.VideoCapture(0)
i = 0

while i < 100:
    _, image = video_feed.read()
    cv.imshow('frame', image)
    grayColor = cv.cvtColor(image, cv.COLOR_BGR2GRAY)
    
    
    ret, corners = cv.findChessboardCorners(
                    grayColor, CHECKERBOARD, 
                    cv.CALIB_CB_ADAPTIVE_THRESH 
                    + cv.CALIB_CB_FAST_CHECK + 
                    cv.CALIB_CB_NORMALIZE_IMAGE)
    if ret == True:
        corners2 = cv.cornerSubPix(grayColor,corners,(11,11),(-1,-1),criteria)
        # Find the rotation and translation vectors.
        ret, matrix, distortion, r_vecs, t_vecs = cv.calibrateCamera(
        objp, corners2, grayColor.shape[::-1], None, None)
        # project 3D points to image plane
        imgpts, jac = cv.projectPoints(axis, rvecs, tvecs, matrix, dist)
        img = draw(img,corners2,imgpts)
        cv.imshow('img',img)
        k = cv.waitKey(0) & 0xFF
        if k == ord('s'):
            cv.imwrite(fname[:6]+'.png', img)
        i = i + 1
#cv.destroyAllWindows()

: 

: 

In [1]:
import cv2
import numpy as np
import os
import glob



def draw(img, corners, imgpts):
    
    imgpts = (np.rint(imgpts)).astype(int)
    corner = tuple(corners[0].ravel())
    corner_1 = tuple(corners[0].ravel())
    corner_2 = tuple(corners[8].ravel())
    corner_3 = tuple(corners[0].ravel())
    x = [int(i) for a, i in enumerate(corner)]
    corner = tuple(x)
    img = cv2.line(img, corner, tuple(imgpts[0].ravel()), (255,0,0), 5)
    img = cv2.line(img, corner, tuple(imgpts[1].ravel()), (0,255,0), 5)
    img = cv2.line(img, corner, tuple(imgpts[2].ravel()), (0,0,255), 5)
    return img



# Define the dimensions of checkerboard
CHECKERBOARD = (6, 9)
  
  
# stop the iteration when specified
# accuracy, epsilon, is reached or
# specified number of iterations are completed.
criteria = (cv2.TERM_CRITERIA_EPS + 
            cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
  
  
# Vector for 3D points
threedpoints = []
  
# Vector for 2D points
twodpoints = []
  
  
#  3D points real world coordinates
objectp3d = np.zeros((CHECKERBOARD[0] 
                      * CHECKERBOARD[1], 
                      3), np.float32)
objectp3d[:, :2] = np.mgrid[0:CHECKERBOARD[0],
                               0:CHECKERBOARD[1]].T.reshape(-1, 2)
prev_img_shape = None
  
  
# Extracting path of individual image stored
# in a given directory. Since no path is
# specified, it will take current directory
# jpg files alone
#images = glob.glob('./Images/*.jpg')
video_feed = cv2.VideoCapture(0)
i = 0
axis = np.float32([[3,0,0], [0,3,0], [0,0,-3]]).reshape(-1,3)
while i < 10:
    _, image = video_feed.read()
    #cv2.imshow('frame', image)
    grayColor = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    #print(i)
    i = i + 1
    # Find the chess board corners
    # If desired number of corners are
    # found in the image then ret = true
    ret, corners = cv2.findChessboardCorners( grayColor, CHECKERBOARD, None)
  
    # If desired number of corners can be detected then,
    # refine the pixel coordinates and display
    # them on the images of checker board
    if ret == True:
        threedpoints.append(objectp3d)
  
        # Refining pixel coordinates
        # for given 2d points.
        corners2 = cv2.cornerSubPix(
            grayColor, corners, (11, 11), (-1, -1), criteria)
  
        twodpoints.append(corners2)
  
        # Draw and display the corners
        # image = cv2.drawChessboardCorners(image, 
        #                                   CHECKERBOARD, 
        #                                   corners2, ret)
        ret, r_vecs, t_vecs = cv2.solvePnP(objectp3d, corners2)
        #imgpts, jac = cv2.projectPoints(axis, r_vecs, t_vecs, matrix, distortion)
        img = draw(image,corners2,imgpts)
        cv2.imshow('img',img)
        #print(len(r_vecs))
        
  
    cv2.imshow('img', image)
    cv2.waitKey(100)
  
cv2.destroyAllWindows()
  
h, w = image.shape[:2]
  
  
# Perform camera calibration by
# passing the value of above found out 3D points (threedpoints)
# and its corresponding pixel coordinates of the
# detected corners (twodpoints)
# ret, matrix, distortion, r_vecs, t_vecs = cv2.calibrateCamera(
#     threedpoints, twodpoints, grayColor.shape[::-1], None, None)
  
  
# Displaying required output
# print(" Camera matrix:")
# print(matrix)
  
# print("\n Distortion coefficient:")
# print(distortion)
  
# print("\n Rotation Vectors:")
# print(r_vecs)
  
# print("\n Translation Vectors:")

# print(t_vecs)

In [16]:
import cv2
import time


video_feed = cv2.VideoCapture(0)
video_feed.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)
video_feed.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)

time.sleep(2)

_, img = video_feed.read()
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

ret, corners = cv2.findChessboardCorners(img, (6, 9), None)
corners_int = corners.astype(int)
corners = tuple(map(tuple, corners_int.reshape(-1, 2)))
print(corners)
for i in range(len(corners)):
    cv2.circle(img, corners[i], 1, (0,0,255), 1)
    cv2.putText(img, str(i), corners[48], cv2.FONT_HERSHEY_DUPLEX, 1, (0,0,255), 1, cv2.LINE_AA)

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()
warp_img = cv2.warpPerspective(img, rotation, (img.shape[0], img.shape[1]))


[ WARN:0@95739.672] global cap_v4l.cpp:982 open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ERROR:0@95739.794] global obsensor_uvc_stream_channel.cpp:156 getStreamChannelGroup Camera index out of range


error: OpenCV(4.8.0) /io/opencv/modules/highgui/src/window.cpp:971: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'imshow'


In [3]:
import cv2
import time


video_feed = cv2.VideoCapture(-1)
video_feed.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)
video_feed.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)

time.sleep(2)

while True:
    _, img = video_feed.read()

    warp_img = cv2.warpPerspective(img, h, (img.shape[1], img.shape[0]))

    cv2.imshow('img', warp_img)

    if cv2.waitKey(1) & 0xFF == ord('q'):
      break

cv2.destroyAllWindows()
video_feed.release()


In [45]:
corners = tuple(corners.reshape(-1, 2))
len(corners)

array([1150.7483 ,  398.32263], dtype=float32)

In [49]:
index = [0, 5, 48, 53]

(1137.5527, 430.67288)

In [154]:
import cv2
import numpy as np
x = src_pts[0, 0]
y = src_pts[0, 1]
d_x = 36
d_y = 15
des_pts = np.array([src_pts[0], [x,y+d_y], [x+d_x,y], [x+d_x,y+d_y]])

h, status = cv2.findHomography(src_pts, des_pts)

In [73]:
a = tuple(map(int, corners))
a

TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'

In [92]:
img = cv2.circle(img, corners_int_tuple[0], 1, (0,0,255), 5)
cv2.putText(img, '3', corners_int_tuple[0], cv2.FONT_HERSHEY_DUPLEX, 0.1, (0,0,255), 1, cv2.LINE_AA)
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [150]:
corners_int_tuple = tuple(map(tuple, corners_int.reshape(-1, 2)))
src_pts = np.array([corners_int_tuple])
src_pts = src_pts.reshape(-1, 2)[[5, 53, 0, 48], :]

In [153]:
src_pts[0, 0]

1120

In [7]:
import cv2
import time
import numpy as np


video_feed = cv2.VideoCapture(-1)
video_feed.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)
video_feed.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)

time.sleep(2)

_, img = video_feed.read()

ret, corners = cv2.findChessboardCorners(img, (6, 9), None)
corners_int = corners.astype(int)
corners_int_tuple = tuple(map(tuple, corners_int.reshape(-1, 2)))
src_pts = np.array([corners_int_tuple])
#src_pts = src_pts.reshape(-1, 2)[[5, 53, 0, 48], :]
src_pts = src_pts.reshape(-1, 2)[[48, 0, 53, 5], :]
for i in range(len(src_pts)):
    cv2.circle(img, src_pts[i], 1, (0,0,255), 1)
    cv2.putText(img, str(i), src_pts[i], cv2.FONT_HERSHEY_DUPLEX, 1, (0,0,255), 1, cv2.LINE_AA)

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()


x = src_pts[0, 0]
y = src_pts[0, 1]
scale = 7
d_x = 8*scale
d_y = 5*scale
y_offset = -50
x_offset = -100

des_pts = np.array([src_pts[0], [x+d_x,y], [x,y+d_y], [x+d_x,y+d_y]])
des_pts[:,0] = des_pts[:,0] + x_offset
des_pts[:,1] = des_pts[:,1] + y_offset
h, status = cv2.findHomography(src_pts, des_pts)

warp_img = cv2.warpPerspective(img, h, (img.shape[1], img.shape[0]))

cv2.imshow('img', warp_img)
cv2.waitKey(0)
cv2.destroyAllWindows()
video_feed.release()

In [192]:
len(src_pts)

4

In [209]:
src_pts.shape

(4, 2)

In [1]:
import cv2
import time
import numpy as np


video_feed = cv2.VideoCapture(-1)
video_feed.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)
video_feed.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)

time.sleep(2)

while True:
    _, img = video_feed.read()
    print(_, end='\r')
    ret, corners = cv2.findChessboardCorners(img, (6, 9), None)
    if ret:
        corners_int = corners.astype(int)
        corners_int_tuple = tuple(map(tuple, corners_int.reshape(-1, 2)))
        src_pts = np.array([corners_int_tuple])
        #src_pts = src_pts.reshape(-1, 2)[[5, 53, 0, 48], :]
        src_pts = src_pts.reshape(-1, 2)[[48, 0, 53, 5], :]
        for i in range(len(src_pts)):
            cv2.circle(img, src_pts[i], 1, (0,0,255), 1)
            cv2.putText(img, str(i), src_pts[i], cv2.FONT_HERSHEY_DUPLEX, 1, (0,0,255), 1, cv2.LINE_AA)

    



    x = src_pts[0, 0]
    y = src_pts[0, 1]
    scale = 7
    d_x = 8*scale
    d_y = 5*scale
    y_offset = -50
    x_offset = -100

    if ret:
       
        des_pts = np.array([src_pts[0], [x+d_x,y], [x,y+d_y], [x+d_x,y+d_y]])
        des_pts[:,0] = des_pts[:,0] + x_offset
        des_pts[:,1] = des_pts[:,1] + y_offset
        h, status = cv2.findHomography(src_pts, des_pts)

        warp_img = cv2.warpPerspective(img, h, (img.shape[1], img.shape[0]))

        cv2.imshow('img', warp_img)


    if cv2.waitKey(1) & 0xFF == ord('q'):
      break
cv2.waitKey(0)
cv2.destroyAllWindows()
video_feed.release()

In [2]:
np.save('h_from_board.npy', h)